FROM marceloagmelo/golang-1.13

USER root

ENV APP_HOME /go/src/github.com/marceloagmelo/go-teste-conexao

COPY Dockerfile $IMAGE_SCRIPTS_HOME/Dockerfile
ADD . $APP_TEMP
ADD scripts $IMAGE_SCRIPTS_HOME

WORKDIR $APP_HOME

RUN go mod init && \
   # CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o go-teste-conexao && \
    go install && \
    chmod 755 $APP_HOME/go-teste-conexao && \
    chown -R golang:golang $APP_HOME && \
    rm -Rf /tmp/* && rm -Rf /var/tmp/*

#######################################################################
##### We have to expose image metada as label and ENV
#######################################################################
LABEL br.com.santander.imageowner="Corporate Techonology" \
      br.com.santander.description="Teste de conexao runtime for node microservices" \
      br.com.santander.components="Golang Server"

ENV br.com.santander.imageowner="Corporate Techonology"
ENV br.com.santander.description="Teste de conexao runtime for node microservices"
ENV br.com.santander.components="Golang Server"

EXPOSE 8080

USER golang

WORKDIR $IMAGE_SCRIPTS_HOME

ENTRYPOINT [ "./control.sh" ]
CMD [ "start" ]