export MYSQL_USER="user"
export MYSQL_PASSWORD="user123"
export MYSQL_ROOT_PASSWORD="admin123"
export MYSQL_DATABASE="mysqldbsample"


export MONGO_INITDB_ROOT_USERNAME="user"
export MONGO_INITDB_ROOT_PASSWORD="user123"
export MONGO_INITDB_DATABASE="mongodbsample"

export RABBITMQ_DEFAULT_USER="user"
export RABBITMQ_DEFAULT_PASS="user123"
export RABBITMQ_ERLANG_COOKIE="12345"
export RABBITMQ_DEFAULT_VHOST="/"